import 'dart:convert';
import 'dart:io';
import '../../test/support/recommendation_fixture.dart';
import 'package:adaptive_workout/domain/logging/program_log.dart';
import 'package:adaptive_workout/domain/logging/practice_repository.dart';
import 'package:adaptive_workout/domain/recommendations/recommendation_history.dart';

void main(List<String> args) {
  final plan = generatedPlan(at: generatedTime.add(const Duration(microseconds: 123457)));
  final start = generatedStart(plan);
  final recorded = start.record(generatedActual(), start.updatedAt.add(const Duration(seconds: 1)), plan);
  final pain = recorded.record(generatedActual(index: 2, validity: SetValidity.pain), recorded.updatedAt.add(const Duration(seconds: 1)), plan);
  final corrected = pain.record(generatedActual(index: 2), pain.updatedAt.add(const Duration(seconds: 1)), plan);
  final ended = corrected.finish(corrected.updatedAt.add(const Duration(seconds: 1)), OccurrenceStatus.completed, plan);
  final j = plan.toJson();
  final slots = (j['slots'] as List).cast<Map<String, Object?>>();
  final targets = (slots[0]['targets'] as List).cast<Map<String, Object?>>();
  targets[0]['minRir'] = null;
  targets[0]['maxRir'] = null;
  targets[0]['rehearsalIdentity'] = RehearsalIdentity(exerciseId: 'warmup_press', setupId: 'warmup_machine', setupRevision: 2, convention: LoadConvention.machineSetting, verificationReference: 'warmup_ref').toJson();
  final v2 = RecommendationSnapshot.decode(jsonEncode({
    'schema': 2,
    'generationReferences': {'bindings':'fixture_bindings_v1','warmup':'fixture_warmup_v2'},
    'slotReasons': {'press':'first_exposure'},
    'proposedLoads': {'press':105000000},
    for(final e in j.entries) if(e.key!='schema') e.key:e.value,
  }));
  final fixtures = <String,String>{
    'plan_v1':plan.encode(),'plan_v2':v2.encode(),'start':start.encode(),'recorded':recorded.encode(),
    'pain':pain.encode(),'corrected':corrected.encode(),'completed':ended.encode(),
    'plan_receipt':jsonEncode({'operation':'recommendation','payload':plan.encode()}),
    'start_receipt':jsonEncode({'operation':'occurrence','expectedRevision':-1,'expectedHistoryRevision':0,'payload':start.encode()}),
  };
  final out=StringBuffer('// Generated by native/Tools/generate_recommendation_goldens.dart on 2026-09-24.\n// Synthetic data only; preserves Dart schema and receipt byte contracts.\nenum RecommendationGoldenFixtures {\n    static let values: [String: String] = [\n');
  for(final e in fixtures.entries) { out.writeln('        "${e.key}": #"${e.value}"#,'); }
  out.writeln('    ]\n}');
  File(args.single).writeAsStringSync(out.toString());
}
