import 'dart:convert';
import 'dart:io';
import '../../lib/domain/workout/owner_program.dart';
import '../../lib/domain/logging/program_log.dart';
import '../../lib/domain/logging/practice_repository.dart';
void main(List<String> args) {
  final fixtures = <String,String>{};
  for (final version in [legacyOwnerProgramVersion,ownerProgramVersion]) {
    for (final plan in ownerProgramForVersion(version)) {
      fixtures['${version}_${plan.id}'] = jsonEncode({
        'id':plan.id,'day':plan.day,'title':plan.title,'blocks':plan.blocks.map((b)=>{
          'rest':b.restSeconds,'exercises':b.exercises.map((e)=>{'id':e.id,'name':e.name,'sets':e.sets,'minReps':e.minReps,'maxReps':e.maxReps,'minRir':e.minRir,'maxRir':e.maxRir,'eachSide':e.eachSide,'alternatives':e.alternatives}).toList(),
        }).toList(),
      });
    }
  }
  var log=ProgramLog(id:'golden',profile:'fixture',programId:'monday',startedAt:DateTime.utc(2026,9,24,12,34,56,123,457),revision:0,completedAt:null,sets:[]);
  fixtures['start']=jsonEncode(log.toJson());
  fixtures['start_receipt']=jsonEncode({'expected':-1,'payload':fixtures['start']});
  log=log.record(ProgramSet(slot:'incline_dumbbell_press',index:1,side:LoggedSide.both,variant:'incline_dumbbell_press',setup:'fixture / హైదరాబాద్ 😀 \n\t"\\\u0000',convention:LoadConvention.perDumbbell,load:30123456,reps:10,rir:2,validity:SetValidity.valid,warmup:false,skipped:false));
  fixtures['set']=jsonEncode(log.toJson());
  fixtures['set_receipt']=jsonEncode({'expected':0,'payload':fixtures['set']});
  log=log.finish(DateTime.utc(2026,9,24,13,34,56,123,457),endEarly:true);
  fixtures['early']=jsonEncode(log.toJson());
  fixtures['early_receipt']=jsonEncode({'expected':1,'payload':fixtures['early']});
  if (args.isEmpty) {
    print(jsonEncode(fixtures));
  } else {
    final out = StringBuffer('// Generated by native/Tools/generate_manual_goldens.dart on 2026-09-24.\n// Synthetic data only; never use personal workout payloads.\nenum ManualGoldenFixtures {\n    static let values: [String: String] = [\n');
    for (final e in fixtures.entries) {
      out.writeln('        "${e.key}": #"${e.value}"#,');
    }
    out.writeln('    ]\n}');
    File(args.single).writeAsStringSync(out.toString());
  }
}
