// Synthetic legacy Dart payloads used by native compatibility tests.
import 'dart:convert';
import 'dart:io';
import '../lib/domain/training/training_setup.dart';
import '../lib/domain/training/setup_variations.dart';
import '../lib/domain/gyms/gym_profile.dart';
import '../lib/domain/logging/practice_repository.dart' as practice;

void main() {
  final at = DateTime.parse('2026-09-23T12:34:56.123456Z');
  final equipment = EquipmentSetup(id: 'machine', revision: 0, label: 'Fixture machine', variation: 'incline_dumbbell_press', equipmentId: 'dumbbells', quantity: 2, capabilities: [], convention: SetupLoadConvention.perDumbbell, workingLoads: [30000000, 20000000], rehearsalLoads: [10000000], confirmedAt: at);
  final baseline = StartingLoad(id: 'baseline', sessionId: 'monday', slotId: 'incline_dumbbell_press', variation: 'incline_dumbbell_press', setupId: 'machine', setupRevision: 0, convention: SetupLoadConvention.perDumbbell, microPounds: 20000000, confirmedAt: at);
  TrainingSetup setup(int schema, {String version = 'owner-program-v2'}) => TrainingSetup(schemaVersion: schema, programVersion: version, reportedWork: schema == 2 ? [ReportedWorkingSetup(id: 'report', sourceReference: 'synthetic_fixture', recordedAt: at, sessionId: 'monday', slotId: 'incline_dumbbell_press', variation: 'incline_dumbbell_press', convention: SetupLoadConvention.perDumbbell, load: 20000000, sets: 3, minReps: null, maxReps: null, minRir: null, maxRir: null, eachSide: false, loadScope: ReportedLoadScope.perHand)] : [], rehearsalConfirmations: schema == 2 ? [RehearsalConfirmation(id: 'rehearsal', sourceReference: 'synthetic_fixture', recordedAt: at, sessionId: 'friday', slotId: 'pull_up', variation: 'unassisted_pull_up', easyAndControlled: true, symptomsReported: false)] : [], profileId: 'synthetic', revision: 0, updatedAt: at, trainingDays: [5,1,3], preferredMinutes: 60, supportedCapabilities: null, unsupportedCapabilities: null, limitations: null, excludedVariations: [], equipment: [equipment], startingLoads: [baseline]);
  final gym = homewoodProfile().update(GymEquipment(category: 'dumbbells', availability: EquipmentAvailability.available, checkedAt: at, notes: 'Synthetic fixture'));
  final record = practice.PracticeSet(id: 'set', exerciseId: 'practice_press', index: 1, microPounds: 12500000, reps: 8, rir: 3, working: true, validity: practice.SetValidity.valid);
  final values = <String, String>{
    'setup1': setup(1).encode(), 'setup2': setup(2).encode(), 'legacySetup': setup(1, version: 'owner-program-v1').encode(),
    'setupReceipt': jsonEncode({'expectedRevision': -1, 'payload': setup(1).encode()}),
    'gym': GymProfiles(selectedId: gym.id, profiles: [gym]).encode(),
    'practiceSet': jsonEncode(record.toJson()),
    'practiceStart': jsonEncode(['start', 'session', at.toIso8601String()]),
    'practiceReceipt': jsonEncode(['set', 'session', 0, record.toJson(), false, at.toIso8601String()]),
  };
  final out = StringBuffer('// Generated by tool/settings_parity_fixtures.dart. Synthetic data only.\nenum SettingsGoldenFixtures {\n    static let values: [String: String] = [\n');
  for (final entry in values.entries) { out.writeln('        "${entry.key}": #"${entry.value}"#,'); }
  out.writeln('    ]\n}');
  File('native/Packages/WorkoutCore/Tests/WorkoutCoreTests/SettingsGoldenFixtures.swift').writeAsStringSync(out.toString());
}
